# FROM indica qual imagem vou me basear ao criar container
FROM nginx:latest 
# RUN executa um comando dentro do meu contêiner
RUN echo "<h1>Kit salve da quebrada!!!</h1>" > /usr/share/nginx/html/index.html